% srun -t 24:00:00 -c 4 --mem=128G --pty matlab -nodisplay -r "LanA_GSS_SN; exit"
function LanA_GSS_SN(i)
% set environment
addpath('/om/group/evlab/software/conn');
conn_module('el','init');

% reduce subjects by inclusion criteria
data = readtable('sessions/final_lang_atlas_sessions.csv');
coverage = readtable('coverage/LanA_cerebellar_coverage.csv');
assert(size(data,1)==size(coverage,1));
% n=3 with only 1 data file, n=49 missing>=50 cerebellar parcels
data = data([data.Runs>=2 & coverage.CerebellumVoxelsMissing<50],:); % n=754

% load in spmfiles
spmfiles = fullfile('/mindhive/evlab/u/Shared/SUBJECTS',data.Session,strcat('firstlevel_',data.Experiment),'SPM.mat')';
for f=1:length(spmfiles)
    assert(isfile(spmfiles{f}));
end

% set up possible cfgs
cfg = {...
    'percentile-ROI-level',0.1,0.1,6;...
    'percentile-ROI-level',0.2,0.1,6;...
    'percentile-ROI-level',0.3,0.1,6;...
    'percentile-ROI-level',0.05,0.1,2;...
    'percentile-ROI-level',0.02,0.1,2;...
    };

spm_ss_estimate(spm_ss_design(struct(...
            'swd',strcat(pwd,'/LanA_GSS_SN_reduced_subjects_percentile-ROI-level_',join(cellfun(@num2str,cfg(i,2:4),'UniformOutput',false),'_')),...
            'EffectOfInterest_spm',{spmfiles},...
            'Localizer_spm',{spmfiles},...
            'EffectOfInterest_contrasts',{{'S-N'}},...
            'Localizer_contrasts',{{'S-N'}},...
            'Localizer_thr_type',cfg{i,1},...
            'Localizer_thr_p',cfg{i,2},...
            'overlap_thr_roi',0,...
            'overlap_thr_vox',cfg{i,3},...
            'type','GcSS',...
            'smooth',cfg{i,4},...
            'model',1,...
            'estimation','OLS',...
            'overwrite',true,...
            'ManualROIs','/nese/mit/group/evlab/u/ccasto/projects/cerebellum/gss/masks/Cerebellum-MNIsegment-1segment.nii',...
            'ExplicitMasking','/nese/mit/group/evlab/u/ccasto/projects/cerebellum/gss/masks/Cerebellum-MNIsegment-1segment.nii',...
            'ask','none'...
            )));
    
end
